server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  main:
    banner-mode: "off"
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl

logging:
  level:
    org:
      springframework: ERROR